### ISSUE TITLE
Unable to extract_redirect_url

### ISSUE THREAD

**Issue by theArnoll** [apple050620312/NCUT-Internet-Auto-Login#1]
When my computer needs to login, it seems can't extract the redirect url.
I'll assume that something is going on in the def on line 23.
I can update more info after 10 hrs, after my computer disconnect again.

**Comment by apple050620312** [comment]
Hello, I've updated a new version, please try and see if it works, I added the option to define ip_segment by user, so you may need to reconfigure it.

**Comment by theArnoll** [comment]
I see. I've downloaded the latest version. I'll report here if it works or not. Thank you for your developing.

**Comment by apple050620312** [comment]
Hello, looks like this issue didn't have message for a long time, closing this as completed.
